files: 
  - name: "cpu.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
  - name: "extensor/extensor.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
  - name: "memory/memory.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
  - name: "pc/pc.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
  - name: "regs/fetch/fetch.v"
    file_type: "verilogSource-2005"
    is_include_file: false
    include_path: ""
    logical_name: ""
    is_manual: true
hooks: 
  pre_build: 
    []
  post_build: 
    []
  pre_run: 
    []
  post_run: 
    []
watchers: 
  []
name: processor
tool_options: 
  ghdl: 
    name: ghdl
    installation_path: ""
    config: 
      installation_path: ""
      waveform: vcd
      analyze_options: 
        []
      run_options: 
        []
toplevel: "cpu.v"